/** Filename (lowercase) → highlight.js language id for extensionless files. */
export const CODE_BASENAME_TO_LANGUAGE: Record<string, string> = {
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  'cmakelists.txt': 'cmake',
  gemfile: 'ruby',
  rakefile: 'ruby',
  vagrantfile: 'ruby',
  podfile: 'ruby',
  brewfile: 'ruby',
  caddyfile: 'nginx',
  'nginx.conf': 'nginx',
};

/** File extension → highlight.js language id. */
export const CODE_EXT_TO_LANGUAGE: Record<string, string> = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.jsx': 'javascript',
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.java': 'java',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'scss',
  '.less': 'less',
  '.py': 'python',
  '.pyw': 'python',
  '.pyi': 'python',
  '.php': 'php',
  '.phtml': 'php',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hh': 'cpp',
  '.hxx': 'cpp',
  '.go': 'go',
  '.rs': 'rust',
  '.rb': 'ruby',
  '.erb': 'erb',
  '.rake': 'ruby',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  '.fish': 'bash',
  '.bashrc': 'bash',
  '.zshrc': 'bash',
  '.profile': 'bash',
  '.sql': 'sql',
  '.psql': 'pgsql',
  '.json': 'json',
  '.jsonc': 'json',
  '.json5': 'json',
  '.xml': 'xml',
  '.xsd': 'xml',
  '.xsl': 'xml',
  '.xslt': 'xml',
  '.svg': 'xml',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.vue': 'html',
  '.svelte': 'html',
  '.swift': 'swift',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.scala': 'scala',
  '.sc': 'scala',
  '.cs': 'csharp',
  '.lua': 'lua',
  '.r': 'r',
  '.rmd': 'r',
  '.dockerfile': 'dockerfile',
  '.pl': 'perl',
  '.pm': 'perl',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.m': 'objectivec',
  '.mm': 'objectivec',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.cljc': 'clojure',
  '.edn': 'clojure',
  '.dart': 'dart',
  '.vb': 'vbnet',
  '.fs': 'fsharp',
  '.fsi': 'fsharp',
  '.fsx': 'fsharp',
  '.groovy': 'groovy',
  '.gradle': 'groovy',
  '.jl': 'julia',
  '.f': 'fortran',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.for': 'fortran',
  '.cmake': 'cmake',
  '.cr': 'crystal',
  '.nim': 'nim',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.tex': 'latex',
  '.latex': 'latex',
  '.proto': 'protobuf',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.ini': 'ini',
  '.cfg': 'ini',
  '.conf': 'ini',
  '.properties': 'ini',
  '.toml': 'ini',
  '.bat': 'dos',
  '.cmd': 'dos',
  '.awk': 'awk',
  '.pas': 'delphi',
  '.dpr': 'delphi',
  '.asm': 'x86asm',
  '.s': 'x86asm',
  '.v': 'verilog',
  '.sv': 'verilog',
  '.svh': 'verilog',
  '.vhd': 'vhdl',
  '.vhdl': 'vhdl',
  '.glsl': 'glsl',
  '.vert': 'glsl',
  '.frag': 'glsl',
  '.coffee': 'coffeescript',
  '.d': 'd',
  '.elm': 'elm',
  '.lisp': 'lisp',
  '.cl': 'lisp',
  '.el': 'lisp',
  '.scm': 'scheme',
  '.ss': 'scheme',
  '.pro': 'prolog',
  '.wat': 'wasm',
  '.wast': 'wasm',
  '.nix': 'nix',
  '.nginx': 'nginx',
  '.hbs': 'handlebars',
  '.handlebars': 'handlebars',
  '.twig': 'twig',
  '.diff': 'diff',
  '.patch': 'diff',
  '.ada': 'ada',
  '.adb': 'ada',
  '.ads': 'ada',
  '.haxe': 'haxe',
  '.hx': 'haxe',
  '.re': 'reasonml',
  '.rei': 'reasonml',
  '.pp': 'puppet',
  '.puppet': 'puppet',
  '.as': 'actionscript',
  '.ahk': 'autohotkey',
  '.au3': 'autoit',
  '.coq': 'coq',
  '.vcoq': 'coq',
  '.mdx': 'markdown',
  '.rst': 'plaintext',
  '.adoc': 'asciidoc',
  '.asciidoc': 'asciidoc',
  '.tf': 'hcl',
  '.tfvars': 'hcl',
  '.hcl': 'hcl',
  '.sol': 'javascript',
  '.zig': 'cpp',
  '.mk': 'makefile',
  '.pug': 'pug',
  '.jade': 'pug',
  '.styl': 'stylus',
  '.jinja': 'django',
  '.j2': 'django',
  '.jinja2': 'django',
  '.tcl': 'tcl',
  '.jsonnet': 'json',
  '.libsonnet': 'json',
  '.wgsl': 'glsl',
  '.hlsl': 'hlsl',
  '.env': 'ini',
  '.applescript': 'applescript',
};

const CODE_MIME_TO_LANGUAGE: Record<string, string> = {
  'text/javascript': 'javascript',
  'application/javascript': 'javascript',
  'text/typescript': 'typescript',
  'text/x-java-source': 'java',
  'text/css': 'css',
  'text/x-scss': 'scss',
  'text/x-sass': 'scss',
  'text/x-less': 'less',
  'text/x-python': 'python',
  'text/x-php': 'php',
  'application/x-httpd-php': 'php',
  'text/x-c': 'c',
  'text/x-c++': 'cpp',
  'text/x-go': 'go',
  'text/x-rust': 'rust',
  'text/x-ruby': 'ruby',
  'text/x-shellscript': 'bash',
  'text/x-sql': 'sql',
  'application/sql': 'sql',
  'application/json': 'json',
  'text/xml': 'xml',
  'application/xml': 'xml',
  'text/yaml': 'yaml',
  'text/x-yaml': 'yaml',
  'application/x-yaml': 'yaml',
  'text/x-swift': 'swift',
  'text/x-kotlin': 'kotlin',
  'text/x-scala': 'scala',
  'text/x-csharp': 'csharp',
  'text/x-cs': 'csharp',
  'text/x-lua': 'lua',
  'text/x-r': 'r',
  'text/x-perl': 'perl',
  'application/x-perl': 'perl',
  'text/x-powershell': 'powershell',
  'text/x-objective-c': 'objectivec',
  'text/x-haskell': 'haskell',
  'text/x-erlang': 'erlang',
  'text/x-elixir': 'elixir',
  'text/x-clojure': 'clojure',
  'text/x-dart': 'dart',
  'text/x-vb': 'vbnet',
  'text/x-fsharp': 'fsharp',
  'text/x-groovy': 'groovy',
  'text/x-julia': 'julia',
  'text/x-fortran': 'fortran',
  'text/x-crystal': 'crystal',
  'text/x-nim': 'nim',
  'text/x-ocaml': 'ocaml',
  'text/x-tex': 'latex',
  'application/x-protobuf': 'protobuf',
  'application/graphql': 'graphql',
  'text/x-dockerfile': 'dockerfile',
  'text/x-matlab': 'matlab',
  'text/x-nginx-conf': 'nginx',
  'text/x-toml': 'ini',
  'text/x-zig': 'cpp',
  'text/x-vue': 'html',
  'text/x-svelte': 'html',
  'text/x-jinja2': 'django',
  'text/x-hcl': 'hcl',
  'text/x-terraform': 'hcl',
  'text/x-applescript': 'applescript',
  'text/x-tcl': 'tcl',
  'text/x-stylus': 'stylus',
};

export function attachmentBasename(name: string): string {
  const slash = Math.max(name.lastIndexOf('/'), name.lastIndexOf('\\'));
  return name.slice(slash + 1).toLowerCase();
}

export function attachmentExtension(name: string): string {
  const dot = name.lastIndexOf('.');
  if (dot < 0) return '';
  return name.slice(dot).toLowerCase();
}

export function isCodeFilename(name: string): boolean {
  if (attachmentBasename(name) in CODE_BASENAME_TO_LANGUAGE) return true;
  return attachmentExtension(name) in CODE_EXT_TO_LANGUAGE;
}

export function isCodeMimeType(mimeType: string): boolean {
  return mimeType in CODE_MIME_TO_LANGUAGE;
}

export function codeLanguageFromAttachment(name: string, mimeType: string): string | null {
  const fromBasename = CODE_BASENAME_TO_LANGUAGE[attachmentBasename(name)];
  if (fromBasename) return fromBasename;
  const fromMime = CODE_MIME_TO_LANGUAGE[mimeType];
  if (fromMime) return fromMime;
  return CODE_EXT_TO_LANGUAGE[attachmentExtension(name)] ?? null;
}
